name: Build and Release Calc3D

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: win_builder
    steps:
      - name: Debug Info
        run: |
          echo "Starting pipeline"
          echo "Ref: ${{ gitea.ref }}"
          echo "Branch: ${{ gitea.ref_name }}"
          echo "Commit: ${{ gitea.sha }}"
          echo "HOST: ${{ secrets.HOST }}"
          echo "ORG: ${{ secrets.ORG }}"
          echo "REPO: ${{ secrets.REPO }}"
        shell: cmd

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MinGW
        run: |
          set PATH=C:\Qt\Tools\mingw1310_64\bin;%PATH%
          echo "MinGW path set"
        shell: cmd

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="C:\Qt\6.9.0\mingw_64" ../src
        shell: cmd

      - name: Build with MinGW
        run: |
          cd build
          mingw32-make
        shell: cmd

      - name: Prepare Release
        run: |
          mkdir Release
          copy build\Calc3D.exe Release\
          C:\Qt\6.9.0\mingw_64\bin\windeployqt.exe Release\Calc3D.exe
          copy C:\Qt\Tools\mingw1310_64\bin\libgcc_s_seh-1.dll Release\
          copy C:\Qt\Tools\mingw1310_64\bin\libstdc++-6.dll Release\
          copy C:\Qt\Tools\mingw1310_64\bin\libwinpthread-1.dll Release\
        shell: cmd

      - name: Archive Release
        run: |
          cd Release
          7z a Calc3D_Release.zip *
          dir
        shell: cmd

      - name: Get Release URL
        id: get_release
        run: |
          Write-Host "Fetching release URL for tag 1.0.0b"
          $headers = @{
            "Authorization" = "token ${{ secrets.ACCESS_TOKEN }}"
            "Accept" = "application/json"
          }
          $response = Invoke-RestMethod -Uri "https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases/tags/1.0.0b" -Headers $headers -Method Get
          $releaseUrl = $response.url
          Write-Host "Found Release URL: $releaseUrl"
          echo "RELEASE_URL=$releaseUrl" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Upload to Gitea Release
        run: |
          Write-Host "Uploading to Gitea"
          $uploadUrl = "${{ env.RELEASE_URL }}/assets?name=Calc3D_Release.zip"
          Write-Host "URL: $uploadUrl"
          $headers = @{
            "Authorization" = "token ${{ secrets.ACCESS_TOKEN }}"
            "Content-Type" = "multipart/form-data"
          }
          Invoke-RestMethod -Uri $uploadUrl -Headers $headers -Method Post -Form @{attachment = Get-Item "Release/Calc3D_Release.zip"} -Verbose
        shell: pwsh