name: Build and Release Calc3D

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: win_builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MinGW
        run: |
          set PATH=C:\Qt\Tools\mingw1310_64\bin;%PATH%
        shell: cmd

      - name: Configure CMake
        run: |          
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="C:\Qt\6.9.0\mingw_64" ../src
        shell: cmd

      - name: Build with MinGW
        run: |          
          cd build
          mingw32-make
        shell: cmd

      - name: Prepare Release
        run: |
          mkdir Release
          copy build\Calc3D.exe Release\
          C:\Qt\6.9.0\mingw_64\bin\windeployqt.exe Release\Calc3D.exe
          copy C:\Qt\Tools\mingw1310_64\bin\libgcc_s_seh-1.dll Release\
          copy C:\Qt\Tools\mingw1310_64\bin\libstdc++-6.dll Release\
          copy C:\Qt\Tools\mingw1310_64\bin\libwinpthread-1.dll Release\
        shell: cmd

      - name: Archive Release
        run: |
          cd Release
          7z a Calc3D_Release.zip *
        shell: cmd

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: Calc3D_Release
          path: Release/Calc3D_Release.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: win_builder
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Calc3D_Release

      - name: Upload to Gitea Release
        run: |
          curl -X POST \
            "https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases/1.0.0b/assets?name=Calc3D_Release.zip" \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "Content-Type: multipart/form-data" \
            -F "attachment=@Calc3D_Release.zip"
        shell: cmd