name: Build and Release Calc3D

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: win_builder
    steps:
      - name: Debug Info
        run: |
          echo "Starting pipeline"
          echo "Ref: ${{ gitea.ref }}"
          echo "Tag: ${{ gitea.ref_name }}"
          echo "HOST: ${{ secrets.HOST }}"
        shell: cmd

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MinGW
        run: |
          set PATH=C:\Qt\Tools\mingw1310_64\bin;%PATH%
          echo "MinGW path set"
        shell: cmd

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="C:\Qt\6.9.0\mingw_64" ../src
        shell: cmd

      - name: Build with MinGW
        run: |
          cd build
          mingw32-make
        shell: cmd

      - name: Prepare Release
        run: |
          mkdir Release
          copy build\Calc3D.exe Release\
          C:\Qt\6.9.0\mingw_64\bin\windeployqt.exe Release\Calc3D.exe
          copy C:\Qt\Tools\mingw1310_64\bin\libgcc_s_seh-1.dll Release\
          copy C:\Qt\Tools\mingw1310_64\bin\libstdc++-6.dll Release\
          copy C:\Qt\Tools\mingw1310_64\bin\libwinpthread-1.dll Release\
        shell: cmd

      - name: Archive Release
        run: |
          cd Release
          7z a Calc3D_Release.zip *
          dir
        shell: cmd

      - name: Check Tag Condition
        run: |
          echo "Checking tag condition"
          echo "Gitea ref: ${{ gitea.ref }}"
          if startswith "${{ gitea.ref }}" "refs/tags/v"; then echo "Tag matches"; else echo "Tag does not match"; fi
        shell: cmd

      - name: Create Gitea Release
        run: |
          echo "Creating release"
          curl -X POST \
            "https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases" \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\":\"1.0.0b\",\"name\":\"Release 1.0.0b\",\"body\":\"Beta release of Calc3D\"}" \
            -v
        shell: cmd

      - name: Upload to Gitea Release
        run: |
          echo "Uploading to Gitea"
          cd Release
          curl -X POST \
            "https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases/1.0.0b/assets?name=Calc3D_Release.zip" \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "Content-Type: multipart/form-data" \
            -F "attachment=@Calc3D_Release.zip" \
            -v
        shell: cmd