name: Build and Release Calc3D

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: win_builder
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MinGW
        shell: pwsh
        run: |
          $env:PATH = "C:\Qt\Tools\mingw1310_64\bin;" + $env:PATH
          Write-Host "MinGW path set"

      - name: Configure CMake
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "build" -Force
          Set-Location -Path "build"
          cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="C:\Qt\6.9.0\mingw_64" ../src

      - name: Build with MinGW
        shell: pwsh
        run: |
          Set-Location -Path "build"
          mingw32-make

      - name: Prepare Release
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "Release" -Force
          Copy-Item -Path "build\Calc3D.exe" -Destination "Release\"
          & "C:\Qt\6.9.0\mingw_64\bin\windeployqt.exe" "Release\Calc3D.exe"
          Copy-Item -Path "C:\Qt\Tools\mingw1310_64\bin\libgcc_s_seh-1.dll" -Destination "Release\"
          Copy-Item -Path "C:\Qt\Tools\mingw1310_64\bin\libstdc++-6.dll" -Destination "Release\"
          Copy-Item -Path "C:\Qt\Tools\mingw1310_64\bin\libwinpthread-1.dll" -Destination "Release\"

      - name: Archive Release
        shell: pwsh
        run: |
          Set-Location -Path "Release"
          & "7z" a "Calc3D_Release.zip" *
          Get-ChildItem

      - name: Get Release URL
        id: get_release
        shell: pwsh
        run: |
          Write-Host "Fetching release URL for tag 1.0.0b"
          $headers = @{
            "Authorization" = "token ${{ secrets.ACCESS_TOKEN }}"
            "Accept" = "application/json"
          }
          $response = Invoke-RestMethod -Uri "https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases/tags/1.0.0b" -Headers $headers -Method Get
          $releaseUrl = $response.url
          Write-Host "Found Release URL: $releaseUrl"
          echo "RELEASE_URL=$releaseUrl" >> $env:GITHUB_ENV

      - name: Upload to Gitea Release
        shell: pwsh
        run: |
          Write-Host "Uploading to Gitea"
          $uploadUrl = "${{ env.RELEASE_URL }}/assets?name=Calc3D_Release.zip"
          Write-Host "URL: $uploadUrl"
          $headers = @{
            "Authorization" = "token ${{ secrets.ACCESS_TOKEN }}"
            "Content-Type" = "multipart/form-data"
          }
          Invoke-RestMethod -Uri $uploadUrl -Headers $headers -Method Post -Form @{attachment = Get-Item "Release/Calc3D_Release.zip"} -Verbose