name: Build and Release Calc3D

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: win_builder
    steps:
      - name: Debug Info
        run: |
          echo "Starting pipeline"
          echo "Ref: ${{ gitea.ref }}"
          echo "Branch: ${{ gitea.ref_name }}"
          echo "Commit: ${{ gitea.sha }}"
          echo "HOST: ${{ secrets.HOST }}"
          echo "ORG: ${{ secrets.ORG }}"
          echo "REPO: ${{ secrets.REPO }}"
        shell: cmd

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MinGW
        run: |
          set PATH=C:\Qt\Tools\mingw1310_64\bin;%PATH%
          echo "MinGW path set"
        shell: cmd

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="C:\Qt\6.9.0\mingw_64" ../src
        shell: cmd

      - name: Build with MinGW
        run: |
          cd build
          mingw32-make
        shell: cmd

      - name: Prepare Release
        run: |
          mkdir Release
          copy build\Calc3D.exe Release\
          C:\Qt\6.9.0\mingw_64\bin\windeployqt.exe Release\Calc3D.exe
          copy C:\Qt\Tools\mingw1310_64\bin\libgcc_s_seh-1.dll Release\
          copy C:\Qt\Tools\mingw1310_64\bin\libstdc++-6.dll Release\
          copy C:\Qt\Tools\mingw1310_64\bin\libwinpthread-1.dll Release\
        shell: cmd

      - name: Archive Release
        run: |
          cd Release
          7z a Calc3D_Release.zip *
          dir
        shell: cmd

      - name: Check Branch Condition
        run: |
          echo "Checking branch condition"
          echo "Gitea ref: ${{ gitea.ref }}"
          if "%{{ gitea.ref }}"=="refs/heads/master" (echo "Branch is master") else (echo "Branch is not master")
        shell: cmd

      - name: Create Gitea Release
        run: |
          echo "Creating release"
          echo "URL: https://%{{ secrets.HOST }}/api/v1/repos/%{{ secrets.ORG }}/%{{ secrets.REPO }}/releases"
          curl -X POST \
            "https://%{{ secrets.HOST }}/api/v1/repos/%{{ secrets.ORG }}/%{{ secrets.REPO }}/releases" \
            -H "Authorization: token %{{ secrets.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\":\"1.0.0b\",\"target_commitish\":\"%{{ gitea.sha }}\",\"name\":\"Release 1.0.0b\",\"body\":\"Auto-generated release from master push\"}" \
            -v
        shell: cmd

      - name: Upload to Gitea Release
        run: |
          echo "Uploading to Gitea"
          echo "URL: https://%HOST%/api/v1/repos/%ORG%/%REPO%/releases/tag/1.0.0b/assets?name=Calc3D_Release.zip"
          cd Release
          curl -X POST \
            "https://%HOST%/api/v1/repos/%ORG%/%REPO%/releases/tag/1.0.0b/assets?name=Calc3D_Release.zip" \
            -H "Authorization: token %{{ secrets.ACCESS_TOKEN }}" \
            -H "Content-Type: multipart/form-data" \
            -F "attachment=@Calc3D_Release.zip" \
            -v
        shell: cmd