name: Build and Release Calc3D

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: win_builder
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

#      - name: Set up MinGW
#        run: |
#          set PATH=C:\Qt\Tools\mingw1310_64\bin;%PATH%
#          echo "MinGW path set"
#        shell: cmd
#
#      - name: Configure CMake
#        run: |
#          mkdir build
#          cd build
#          cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="C:\Qt\6.9.0\mingw_64" ../src
#        shell: cmd
#
#      - name: Build with MinGW
#        run: |
#          cd build
#          mingw32-make
#        shell: cmd
#
#      - name: Prepare Release
#        run: |
#          mkdir Release
#          copy build\Calc3D.exe Release\
#          C:\Qt\6.9.0\mingw_64\bin\windeployqt.exe Release\Calc3D.exe
#          copy C:\Qt\Tools\mingw1310_64\bin\libgcc_s_seh-1.dll Release\
#          copy C:\Qt\Tools\mingw1310_64\bin\libstdc++-6.dll Release\
#          copy C:\Qt\Tools\mingw1310_64\bin\libwinpthread-1.dll Release\
#        shell: cmd
#
#      - name: Archive Release
#        run: |
#          cd Release
#          7z a Calc3D_Release.zip *
#          dir
#
#        shell: cmd

#      - name: Create Gitea Release
#        run: |
#          echo "Creating release"
#          echo "URL: https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases/tags/1.0.0b"
#          curl -X POST \
#            "https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases" \
#            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
#            -H "Content-Type: application/json" \
#            -d "{\"tag_name\":\"1.0.0b\",\"target_commitish\":\"${{ gitea.sha }}\",\"name\":\"Release 1.0.0b\",\"body\":\"Auto-generated release from master push\"}" \
#            -v
#        shell: cmd

      - name: Upload to Gitea Release
        run: |
          echo "Fetching release ID for tag 1.0.0b"
          echo "https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases/tags/1.0.0b" \
          curl -v -X GET ^
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" ^
            "https://git.corp.s21party.ru/api/v1/repos/risen/Calc3D_by_Risen/releases/tags/1.0.0b" ^            
            -H "Accept: application/json" ^
            -o release.json
          for /f "tokens=2 delims=:," %%i in ('findstr /C:"\"url\"" release.json') do set URL=%%i
          echo "URL=%URL%" >> %GITHUB_ENV%
          echo "Found Release ID: %URL%"
          
#          echo "Uploading to Gitea"
#          echo "URL: https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases/%RELEASE_ID%/assets?name=Calc3D_Release.zip"
#          cd Release
#          curl -X POST \
#            "https://${{ secrets.HOST }}/api/v1/repos/${{ secrets.ORG }}/${{ secrets.REPO }}/releases/%RELEASE_ID%/assets?name=Calc3D_Release.zip" \
#            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
#            -H "Content-Type: multipart/form-data" \
#            -F "attachment=@Calc3D_Release.zip" \
#            -v
        shell: cmd